const PLAYLISTS = {};

// env vars
const BOT_TOKEN = process.env.BOT_TOKEN;
const TELEGRAM_WEBHOOK_HOST = process.env.TELEGRAM_WEBHOOK_HOST;
const SPOTIFY_CLIENT_ID = process.env.SPOTIFY_CLIENT_ID;
const SPOTIFY_CLIENT_SECRET = process.env.SPOTIFY_CLIENT_SECRET;
const SPOTIFY_REDIRECT_URI =
  process.env.SPOTIFY_REDIRECT_URI || 'http://localhost:3000/spotify/auth';

console.log(`
BOT_TOKEN: ${BOT_TOKEN}
TELEGRAM_WEBHOOK_HOST: ${TELEGRAM_WEBHOOK_HOST}
SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
SPOTIFY_REDIRECT_URI: ${SPOTIFY_REDIRECT_URI}
`);

module.exports = {
  PLAYLISTS,
  BOT_TOKEN,
  SPOTIFY_CLIENT_ID,
  SPOTIFY_CLIENT_SECRET,
  SPOTIFY_REDIRECT_URI,
  TELEGRAM_WEBHOOK_HOST,
};
